package com.lancer.bean;

import java.util.Date;

public class SysLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSLOG.ID
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSLOG.USERNAME
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    private String USERNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSLOG.OPERATION
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    private String OPERATION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSLOG.TIME
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    private Integer TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSLOG.METHOD
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    private String METHOD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSLOG.PARAMS
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    private String PARAMS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSLOG.IP
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    private String IP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSLOG.CREATE_TIME
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    private Date CREATE_TIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSLOG.ID
     *
     * @return the value of SYSLOG.ID
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSLOG.ID
     *
     * @param ID the value for SYSLOG.ID
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSLOG.USERNAME
     *
     * @return the value of SYSLOG.USERNAME
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public String getUSERNAME() {
        return USERNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSLOG.USERNAME
     *
     * @param USERNAME the value for SYSLOG.USERNAME
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public void setUSERNAME(String USERNAME) {
        this.USERNAME = USERNAME == null ? null : USERNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSLOG.OPERATION
     *
     * @return the value of SYSLOG.OPERATION
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public String getOPERATION() {
        return OPERATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSLOG.OPERATION
     *
     * @param OPERATION the value for SYSLOG.OPERATION
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public void setOPERATION(String OPERATION) {
        this.OPERATION = OPERATION == null ? null : OPERATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSLOG.TIME
     *
     * @return the value of SYSLOG.TIME
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public Integer getTIME() {
        return TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSLOG.TIME
     *
     * @param TIME the value for SYSLOG.TIME
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public void setTIME(Integer TIME) {
        this.TIME = TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSLOG.METHOD
     *
     * @return the value of SYSLOG.METHOD
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public String getMETHOD() {
        return METHOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSLOG.METHOD
     *
     * @param METHOD the value for SYSLOG.METHOD
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public void setMETHOD(String METHOD) {
        this.METHOD = METHOD == null ? null : METHOD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSLOG.PARAMS
     *
     * @return the value of SYSLOG.PARAMS
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public String getPARAMS() {
        return PARAMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSLOG.PARAMS
     *
     * @param PARAMS the value for SYSLOG.PARAMS
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public void setPARAMS(String PARAMS) {
        this.PARAMS = PARAMS == null ? null : PARAMS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSLOG.IP
     *
     * @return the value of SYSLOG.IP
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public String getIP() {
        return IP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSLOG.IP
     *
     * @param IP the value for SYSLOG.IP
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public void setIP(String IP) {
        this.IP = IP == null ? null : IP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSLOG.CREATE_TIME
     *
     * @return the value of SYSLOG.CREATE_TIME
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public Date getCREATE_TIME() {
        return CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSLOG.CREATE_TIME
     *
     * @param CREATE_TIME the value for SYSLOG.CREATE_TIME
     *
     * @mbggenerated Sat Oct 26 20:21:26 CST 2019
     */
    public void setCREATE_TIME(Date CREATE_TIME) {
        this.CREATE_TIME = CREATE_TIME;
    }
}